### ISSUE TITLE
Display error when no movie is found

### ISSUE THREAD

**Issue by theshubhagrwl** [theshubhagrwl/MyMovieTime#6]
Implement a small error line or a box when the user makes a typo in searching or her/she searches for a movie that is not available. 
Currently, there is no error handling in the app, it just shows nothing.  
There is no specific requirement, just one that the UI should match with the website's overall look.

**Comment by comrade-om** [comment]
Hi @theshubhagrwl , I would like to contribute to this issue. Shall I give it a try?

**Comment by sarulathadurai** [comment]
hi @theshubhagrwl can I contribute to this issue ?

**Comment by theshubhagrwl** [comment]
Yes please, @comrade-om  and @sarulathadurai  give it a try. I have assigned you both.

**Comment by comrade-om** [comment]
Also a humble request to add hacktoberfest topic to the repo since they updated the [rules](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Comment by comrade-om** [comment]
@theshubhagrwl I don't know why but the project isn't working on my local machine as in it doesn't display any movies what so ever.

**Comment by theshubhagrwl** [comment]
> @theshubhagrwl I don't know why but the project isn't working on my local machine as in it doesn't display any movies what so ever.

Hi, I think you are not having an API key of OMDB API. 
If you want you can request a key here http://www.omdbapi.com/
